### ISSUE TITLE
Use fromDistinctAscList for Data.Set decoding

### ISSUE THREAD

**Issue by axman6** [well-typed/binary-serialise-cbor#113]
I was wondering if there's any reason to not use `fromDistinctAscList` in the decoding of `Data.Set`. Given that the comments for `Data.Set.foldr` state

```haskell
foldr f z == foldr f z . toAscList
```
this should be safe and provide a *log n* improvement in decoding speed. The same appears to be true for `Data.IntSet`. Happy to write the PR is response is positive/no one can think of a good reason not to.

**Comment by Shimuuar** [comment]
> The precondition (input list is strictly ascending) is not checked.

We don't have guarantee that list will be in fact strictly ascending

**Comment by axman6** [comment]
@Shimuuar but the encoding is supposed to guarantee that, because Data.Set.foldr folds over a strictly ascending list. That comment is there to warn the user that `fromDistinctAscList` is only safe if the precondition, that the list is strictly ascending, is met.

**Comment by Shimuuar** [comment]
It's met if blob were produced by this library and haven't been changed. If it's possible to create set in invalid state it could lead to security problems 

We should at least check that list is indeed ascending.

**Comment by axman6** [comment]
I believe there are plenty of places in this library where the only guarantee is that roundtriping is valid - if you're dealing with external data you're always going to have to be more careful - IIRC the library isn't intended so much to be the CBOR library, but the Haskell serialisation library which uses CBOR.

**Comment by Shimuuar** [comment]
Problem here is possibility of creating Set in the invalid state. I think that any general-purpose serialization library should deal with possibility of malicious input. 

Also it _will_ be used for communication with other programs.

**Comment by thoughtpolice** [comment]
Yes, we've specifically tried to harden the library around attacks like this; it's also why the container type instances have so much boilerplate to do 'incremental' ingestion of large containers, so DOS attacks aren't as easy (e.g. a serialized blob says "i have a serialized vector inside of size 0xFFFFFFFF" and GHC allocates that sized buffer for you). Similar problems have plagued e.g. `Data.Binary` too (one allowed you to construct an invalid `Map` from a hostile `binary` value).

Realistically, yes, we're *mostly* aiming for "a haskell serialization library" (general CBOR interop is less important, but a valid use case). But serialization is generally a security boundary precisely because it's an interface boundary, so I think handling malicious input is the right way to go.[1]

---

[1] There is the tidbit that *users* of the library should be aware of these points, e.g. if they write instances for their own container types. However, I think we *should* highlight this point (in the tutorial/docs), and also I imagine many user-defined instances will eventually come down to the core ones shipped with this library, which *we* can control and audit.

**Comment by axman6** [comment]
ok, in that case, there's no need for the PR.

**Comment by thoughtpolice** [comment]
I'll still take the change for the extra few instance tests you added in that commit :) (Curiously, we may be missing a test for `Rational`s instance!)

**Comment by axman6** [comment]
So, thinking about this a bit more, perhaps we could have a module or library which provides these instances for when we're working with trusted data sources and the (hopeful) performance improvement is worthwhile. I imagine there's probably a lot of instances where faster, less safe alternatives might be useful, where might these live?
