### ISSUE TITLE
Compilation with GHC 7.6 fails

### ISSUE THREAD

**Issue by michalt** [well-typed/binary-serialise-cbor#41]
Example from Travis:
https://travis-ci.org/well-typed/binary-serialise-cbor/jobs/117276121

The culprit seems to be the introduction of `orI#` (wasn't there in GHC 7.6) and changes to comparisons (e.g., `>#` used to return `Bool` in GHC 7.6, now returns `Int#`). I guess the main question is: do we want to support GHC 7.6? (since 8.0 release is soon so the last 3 GHC versions would be 7.8, 7.10 and 8.0) If yes, then we'll probably need to have a bunch of `ifdefs`...

**Comment by thoughtpolice** [comment]
Right, I haven't gotten around to fixing this just yet. I'll look at it soon (TL;DR yes, it would be nice to keep 7.6.3, regardless of the course of 8.0.1)

**Comment by thoughtpolice** [comment]
Ugh, for now I've removed it since fixing it requires an annoying amount of work. We'll have to adopt something like [this module](https://github.com/thoughtpolice/ghc-prim-compat/blob/master/src/GHC/Exts/Compat.hs) to fix it and change up the types. I'm open to fixing this, but in the mean time I want to get the CI working again ASAP.

**Comment by thoughtpolice** [comment]
(See also f6729309caa1dc6416b239fa68905d391eae1043 in the `fix-ghc7.6` branch.)

**Comment by thoughtpolice** [comment]
8.0 is shelved to be released Any Moment Now, so I'm tentatively removing this from the initial release milestone and marking as low.

**Comment by thoughtpolice** [comment]
I'm closing this to clean up the issue tracker; 8.2 is due Real Soon now and we'll be supporting ~4 years of GHC versions at that point, which I think is pretty good anyway.

I wouldn't reject a patch for 7.6 support if someone came and added it, but I no longer plan on tackling this myself due to it adding a fair bit of code and some fiddling (and I doubt any of the rest of us doing primary development would want to do it, either).
