### ISSUE TITLE
UTCTime tag 1 is not handled

### ISSUE THREAD

**Issue by thoughtpolice** [well-typed/binary-serialise-cbor#61]
According to [the RFC](https://tools.ietf.org/html/rfc7049#section-2.4.1), encoded UTC time values can use a 0 tag to represent a serialized string in ISO-8601 format, or tag 1 to represent a numeric representation, of the number of seconds passed since the UNIX epoch.

[As of today](https://github.com/well-typed/binary-serialise-cbor/blob/feaf9d33703fb3ed2fd56df2c7ec293b8210f5b4/Data/Binary/Serialise/CBOR/Class.hs#L728), we don't handle tag 1. That should be fixed before release (and is probably fairly easy).

See also #51 - it's important to make sure this case is efficient as well (and that's probably easier than the tag 0 case).

**Comment by axman6** [comment]
I've added a pull request for this (#68), I assume there's no plan to replace the RFC 3339 based serialisation of UTCTimes because it's not as easy to get the accuracy of the text based implementation  (my quick testing using Doubles with tag 1 turned up examples where decode . encode /= id quite quickly). We could in theory check to see if the encoded value can be precisely encoded using Int/Double and only when it can't resort to the RFC 3339 text, but that might be more hassle than its worth (and the textual representation is nicer to debug when using things like the .Pretty printer).

**Comment by thoughtpolice** [comment]
Definitely more hassle than it's worth, and I strongly prefer the default interface yielding the most accurate representation if possible (although see #51, and I'm open to changing this before the actual release). I suggest we document only that we handle non-String-y `UTCTime` tag values as a matter of compatibility with the RFC (or usage of like, the `.Term` module to read out-of-band values that might use e.g. Floating representation).

**Comment by axman6** [comment]
Maybe we could also have a newtype around UTCTime which uses the most appropriate numeric representation for the time given (or just Int64/Double, to make our lives easier). I can imagine cases where people would want to specify the numeric version for space/efficiency reasons.
